version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: webpack
    versions:
    - 5.27.1
    - 5.28.0
    - 5.34.0
  - dependency-name: css-loader
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: underscore
    versions:
    - 1.13.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
